[2022-04-30 12:01:21,306] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: btc_spot_data_dag.results manual__2022-04-30T12:01:04.681211+00:00 [queued]>
[2022-04-30 12:01:21,322] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: btc_spot_data_dag.results manual__2022-04-30T12:01:04.681211+00:00 [queued]>
[2022-04-30 12:01:21,322] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 12:01:21,323] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-30 12:01:21,323] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 12:01:21,392] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): results> on 2022-04-30 12:01:04.681211+00:00
[2022-04-30 12:01:21,399] {standard_task_runner.py:52} INFO - Started process 4390 to run task
[2022-04-30 12:01:21,403] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'btc_spot_data_dag', 'results', 'manual__2022-04-30T12:01:04.681211+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmps2ut8yys', '--error-file', '/tmp/tmptmti51z0']
[2022-04-30 12:01:21,405] {standard_task_runner.py:80} INFO - Job 107: Subtask results
[2022-04-30 12:01:21,477] {logging_mixin.py:109} INFO - Running <TaskInstance: btc_spot_data_dag.results manual__2022-04-30T12:01:04.681211+00:00 [running]> on host cf4e030da5d2
[2022-04-30 12:01:21,566] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=btc_spot_data_dag
AIRFLOW_CTX_TASK_ID=results
AIRFLOW_CTX_EXECUTION_DATE=2022-04-30T12:01:04.681211+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-30T12:01:04.681211+00:00
[2022-04-30 12:01:21,568] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/results.py", line 2, in _calculate_results
    print("asks:" + str(kwargs['asks']))
KeyError: 'asks'
[2022-04-30 12:01:21,587] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=btc_spot_data_dag, task_id=results, execution_date=20220430T120104, start_date=20220430T120121, end_date=20220430T120121
[2022-04-30 12:01:21,604] {standard_task_runner.py:98} ERROR - Failed to execute job 107 for task results ('asks'; 4390)
[2022-04-30 12:01:21,617] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-30 12:01:21,657] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
