[2022-04-30 08:19:18,625] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: btc_spot_data_dag.aggregated_daily_bids manual__2022-04-30T08:19:10.071355+00:00 [queued]>
[2022-04-30 08:19:18,645] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: btc_spot_data_dag.aggregated_daily_bids manual__2022-04-30T08:19:10.071355+00:00 [queued]>
[2022-04-30 08:19:18,646] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 08:19:18,646] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-30 08:19:18,647] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 08:19:18,669] {taskinstance.py:1270} INFO - Executing <Task(BigQueryOperator): aggregated_daily_bids> on 2022-04-30 08:19:10.071355+00:00
[2022-04-30 08:19:18,676] {standard_task_runner.py:52} INFO - Started process 2925 to run task
[2022-04-30 08:19:18,683] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'btc_spot_data_dag', 'aggregated_daily_bids', 'manual__2022-04-30T08:19:10.071355+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp_dr3etbk', '--error-file', '/tmp/tmp2979xvwk']
[2022-04-30 08:19:18,684] {standard_task_runner.py:80} INFO - Job 34: Subtask aggregated_daily_bids
[2022-04-30 08:19:18,805] {logging_mixin.py:109} INFO - Running <TaskInstance: btc_spot_data_dag.aggregated_daily_bids manual__2022-04-30T08:19:10.071355+00:00 [running]> on host 7356a9a87c5b
[2022-04-30 08:19:18,910] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=btc_spot_data_dag
AIRFLOW_CTX_TASK_ID=aggregated_daily_bids
AIRFLOW_CTX_EXECUTION_DATE=2022-04-30T08:19:10.071355+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-30T08:19:10.071355+00:00
[2022-04-30 08:19:18,911] {bigquery.py:655} INFO - Executing: 
            #legacySql
            select sum(bids.size) from `btcspot.btcspot.bids` as bids group by timestamp;
            
[2022-04-30 08:19:18,949] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 661, in execute
    impersonation_chain=self.impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 108, in __init__
    impersonation_chain=impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 219, in __init__
    self.extras = self.get_connection(self.gcp_conn_id).extra_dejson  # type: Dict
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 410, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2022-04-30 08:19:18,966] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=btc_spot_data_dag, task_id=aggregated_daily_bids, execution_date=20220430T081910, start_date=20220430T081918, end_date=20220430T081918
[2022-04-30 08:19:18,996] {standard_task_runner.py:98} ERROR - Failed to execute job 34 for task aggregated_daily_bids (The conn_id `google_cloud_default` isn't defined; 2925)
[2022-04-30 08:19:19,016] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-30 08:19:19,075] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
